-- CON USING PERMITE SOLAMENTE COGER LOS NUMERO SIN EL SIGNO OSEA SOLAMENTE POSITIVOS
-- not null significa que no es nada 
-- null kiere decir que no hay nada almacenado
-- una cadena vacio kiere decir que hay un vacio almacenado
-- DEFAULT NUMERO = UN NUMERO X DEFECTO EN EL CAMPO
-- LO QUE SE GUARDA EN LA BASE DE DATOS EN CUANTO LAS IMAGENES SON LAS RUTAS DONDE SE ENCUENTRA DICHA IMAGEN
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER UNSING PRIMARY AUTO_INCREMENT,
    author,
    title varchar(100) NOT NULL,
    YEAR integer unsigned NOT NULL DEFAULT 19900,
    LANGUAGE VARCHAR(2)NOT NULL DEFAULT 'es' COMMENT 'ISO 639-1 LANGUAGE',
    COVER_URL VARCHAR(255),
    PRICE DOUBLE (4,2) NOT NULL DEFAULT 10.0,
    SELLABLE TINYINT(1) DEFAULT 1,
    COPIES INTEGER NOT NULL DEFAULT 01,
    DESCRIPTION TEXT,
    
);